### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by traktofon** [berquist/chargemol#2]
Hello,

this repository currently states

> There is no license other than "rights reserved" by the original authors.

However, the original zip file `chargemol_09_26_2017.zip` includes a PDF `instructions_09_26_2017.pdf` which on page 6 contains a section (A4) about licensing information. It may be worthwile to add that information to this repository.

The authors claim that their license is OSI-compliant, though notably it contains the condition

> The source code is restricted from being distributed in modified form; however, this license allows the distribution of “patch files” with the source code for the purpose of modifying the program at build time.

which one must bear in mind when modifying the code. There's also a requirement for citing certain academic publications of the authors when publishing results. This is certainly reasonable but users should be made aware of it.

Somewhat relatedly, I'm not sure how useful this repository is without the `atomic_densities` directory. It seems to be required for some (perhaps all) calculations. The licensing information only talks about "software" and "source code" so it's not clear whether it also applies to the data files from `atomic_densities`. But as the data files are originally distributed along with the software, perhaps it's reasonable to assume they are covered by the same license?

**Comment by berquist** [comment]
I think I put the code here just so someone else who was working with it could build it more generally via CMake, rather than whatever it was using before.  They already had a copy of the atomic densities.  But I agree on all points (include more detailed license info plus additional requirements, include atomic densities).

**Comment by berquist** [comment]
I've added the atomic densities in 569abf08d071a794f85259383236d619c2c3ed04, the user manual in 2aff6ec95fc3fb041cd77c911acbd98406071c12, and the README converted to Markdown with the license verbiage from the manual added in bd8c129db178cf8db6bfbe056d924ac1b64920ab.
